name: ci-node-calculator

on: 
  pull_request: 
    branches: 
      - develop
      
jobs: 
  check-application: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - run: yarn install
      - run: yarn test
      - run: node src/calculator.js